/**
 * Order domain constants.
 */
export const ORDER_LIMITS = {
  /** Default currency. */
  DEFAULT_CURRENCY: 'VND',
  /** Default locale. */
  DEFAULT_LOCALE: 'vi-VN',
  /** Max items per order. */
  MAX_ITEMS_PER_ORDER: 100,
  /** Pagination defaults. */
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 200,
} as const;

export const ORDER_ERROR_CODES = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_EXISTS: 'ORDER_ALREADY_EXISTS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  CHECKOUT_NOT_READY: 'CHECKOUT_NOT_READY',
  CHECKOUT_NO_RESERVATION: 'CHECKOUT_NO_RESERVATION',
  CHECKOUT_RESERVATION_NOT_ACTIVE: 'CHECKOUT_RESERVATION_NOT_ACTIVE',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_ALREADY_COMPLETED: 'ORDER_ALREADY_COMPLETED',
  ORDER_DELIVERED_CANNOT_CANCEL: 'ORDER_DELIVERED_CANNOT_CANCEL',
  UNAUTHORIZED_ORDER_ACCESS: 'UNAUTHORIZED_ORDER_ACCESS',
  EMPTY_ORDER: 'EMPTY_ORDER',
  INVALID_ORDER_DATA: 'INVALID_ORDER_DATA',
} as const;

export type OrderErrorCode =
  (typeof ORDER_ERROR_CODES)[keyof typeof ORDER_ERROR_CODES];
